// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ras/protocol/v1/param.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ras.Protocol.V1 {

  /// <summary>Holder for reflection information generated from ras/protocol/v1/param.proto</summary>
  public static partial class ParamReflection {

    #region Descriptor
    /// <summary>File descriptor for ras/protocol/v1/param.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ParamReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtyYXMvcHJvdG9jb2wvdjEvcGFyYW0ucHJvdG8SD3Jhcy5wcm90b2NvbC52",
            "MSJNCgVQYXJhbRIuCgR0eXBlGAEgASgOMhoucmFzLnByb3RvY29sLnYxLlBh",
            "cmFtVHlwZVIEdHlwZRIUCgV2YWx1ZRgCIAEoDFIFdmFsdWUqiwIKCVBhcmFt",
            "VHlwZRIWChJQQVJBTV9VTktOT1dOX1RZUEUQABIRCg1QQVJBTV9CT09MRUFO",
            "EAESDgoKUEFSQU1fQllURRACEg8KC1BBUkFNX1NIT1JUEAMSDQoJUEFSQU1f",
            "SU5UEAQSDgoKUEFSQU1fTE9ORxAFEg8KC1BBUkFNX0ZMT0FUEAYSEAoMUEFS",
            "QU1fRE9VQkxFEAcSDgoKUEFSQU1fU0laRRAIEhcKE1BBUkFNX05VTExBQkxF",
            "X1NJWkUQCRIQCgxQQVJBTV9TVFJJTkcQChIOCgpQQVJBTV9VVUlEEAsSDgoK",
            "UEFSQU1fVFlQRRAMEhUKEVBBUkFNX0VORFBPSU5UX0lEEA1CvAEKE2NvbS5y",
            "YXMucHJvdG9jb2wudjFCClBhcmFtUHJvdG9QAVo7Z2l0aHViLmNvbS92OHBs",
            "YXRmb3JtL3Byb3Rvcy9nZW4vcmFzL3Byb3RvY29sL3YxO3Byb3RvY29sdjGi",
            "AgNSUFiqAg9SYXMuUHJvdG9jb2wuVjHKAg9SYXNcUHJvdG9jb2xcVjHiAhtS",
            "YXNcUHJvdG9jb2xcVjFcR1BCTWV0YWRhdGHqAhFSYXM6OlByb3RvY29sOjpW",
            "MWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Ras.Protocol.V1.ParamType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ras.Protocol.V1.Param), global::Ras.Protocol.V1.Param.Parser, new[]{ "Type", "Value" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ParamType {
    [pbr::OriginalName("PARAM_UNKNOWN_TYPE")] ParamUnknownType = 0,
    [pbr::OriginalName("PARAM_BOOLEAN")] ParamBoolean = 1,
    [pbr::OriginalName("PARAM_BYTE")] ParamByte = 2,
    [pbr::OriginalName("PARAM_SHORT")] ParamShort = 3,
    [pbr::OriginalName("PARAM_INT")] ParamInt = 4,
    [pbr::OriginalName("PARAM_LONG")] ParamLong = 5,
    [pbr::OriginalName("PARAM_FLOAT")] ParamFloat = 6,
    [pbr::OriginalName("PARAM_DOUBLE")] ParamDouble = 7,
    [pbr::OriginalName("PARAM_SIZE")] ParamSize = 8,
    [pbr::OriginalName("PARAM_NULLABLE_SIZE")] ParamNullableSize = 9,
    [pbr::OriginalName("PARAM_STRING")] ParamString = 10,
    [pbr::OriginalName("PARAM_UUID")] ParamUuid = 11,
    [pbr::OriginalName("PARAM_TYPE")] ParamType = 12,
    [pbr::OriginalName("PARAM_ENDPOINT_ID")] ParamEndpointId = 13,
  }

  #endregion

  #region Messages
  public sealed partial class Param : pb::IMessage<Param>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Param> _parser = new pb::MessageParser<Param>(() => new Param());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Param> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ras.Protocol.V1.ParamReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Param() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Param(Param other) : this() {
      type_ = other.type_;
      value_ = other.value_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Param Clone() {
      return new Param(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Ras.Protocol.V1.ParamType type_ = global::Ras.Protocol.V1.ParamType.ParamUnknownType;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ras.Protocol.V1.ParamType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 2;
    private pb::ByteString value_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Value {
      get { return value_; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Param);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Param other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Value != other.Value) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Ras.Protocol.V1.ParamType.ParamUnknownType) hash ^= Type.GetHashCode();
      if (Value.Length != 0) hash ^= Value.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Ras.Protocol.V1.ParamType.ParamUnknownType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Ras.Protocol.V1.ParamType.ParamUnknownType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Ras.Protocol.V1.ParamType.ParamUnknownType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Value.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Value);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Param other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Ras.Protocol.V1.ParamType.ParamUnknownType) {
        Type = other.Type;
      }
      if (other.Value.Length != 0) {
        Value = other.Value;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Ras.Protocol.V1.ParamType) input.ReadEnum();
            break;
          }
          case 18: {
            Value = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Ras.Protocol.V1.ParamType) input.ReadEnum();
            break;
          }
          case 18: {
            Value = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
